version: "3.7"

services:
  app:
    container_name: "go-recipe"
    image: golang:1.19.2-bullseye
    ports:
      - 3001:3000
    volumes:
      - ./:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    env_file:
      - .env
    tty: true
    networks:
      - recipe-net

  mongo:
    image: mongo:6.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - recipe-net
      

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - recipe-net


networks:
  recipe-net:
